### ISSUE TITLE
Issues With 'calculatePayroll' Function's Hint

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-1-intro-to-context#3]
### Canvas Link

https://learning.flatironschool.com/courses/5284/assignments/172150?confetti=true&submitted=0

### Concern

The 'calculatePayroll()' function needs more context to be able to handle an embedded array that is given in by the test itself.

More information should be provided as what to expect.

I had to look deeper in the test to even handle this edge case scenario, when most of the other functions expected time in and time out strings vs the final function had to deal with an edge case.

Needs better hints for this with this in mind.

**Comment by AlveeM** [comment]
Hi Samuel, could you tell us more about what kind of information would be helpful for you to solve the problem?

**Comment by AlveeM** [comment]
Hi Samuel, I'm closing this issue as it's been over a month since my last comment. If you have any other suggestions, feel free to reopen this issue or submit a new issue.
