### ISSUE TITLE
Intro to Context: Error in indexTest.js

### ISSUE THREAD

**Issue by tloughrist** [learn-co-curriculum/phase-1-intro-to-context#4]
### Canvas Link

https://learning.flatironschool.com/courses/5641/assignments/198251?module_item_id=448219

### Concern

indexTest.js:

- Error on lines 190, 196: "324" should be "54"
- Error on line 197: "378" should be "108"

Prevents correct code from passing learn test

**Comment by lizbur10** [comment]
Hi @tloughrist - thanks for providing this feedback. The current tests appear to be correct to me. The TimeIn and TimeOut events on lines 191 & 192 indicate 12 hours of work, and 12 * 27 is 324. I'm going to go ahead and close this issue, but please let us know if you still believe there is an error.

Thanks for contributing to the Flatiron School curriculum 💙
